# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def even(x):
	return x % 2 == 0

def problem2(n):
	sum = 0
	a, b = 0, 1
	while a < n:
		print(a, end=' ')
		a, b = b, a+b
		
		if even(a): sum += a

	print()
	print("sum: {}".format(sum))
	
	
problem2(4000000)
